/** Report page behaviour: mounts the Executive Shell from the embedded JSON. */
import { mountExecShell } from './exec-shell.js';

const data = JSON.parse(document.getElementById('report-data').textContent);
const label = (s) => s.replace(/_/g, ' ');
const pts = (v) => `${(v * 100).toFixed(1)} pts`;

const shell = mountExecShell({
  theme: 'midnight',
  title: 'Growth Analytics Engine',
  tagline: 'Markov-chain attribution, cohort retention and lifetime value, randomised-treatment uplift and CAC/LTV economics on one synthetic event stream. Generated by CI; nothing here describes a real programme.',
  repo: 'https://github.com/Freddricklogan/growth-analytics-engine',
  pagesUrl: 'https://freddricklogan.github.io/growth-analytics-engine/',
  badges: [{ label: 'Markov attribution', tone: 'accent' }, { label: 'Randomised uplift', dot: true }, { label: 'Synthetic data', dot: true }],
  kpis: [
    { label: 'Prospects', compute: () => data.users.toLocaleString(), tone: 'accent' },
    { label: 'Enrolments', compute: () => `${data.converted.toLocaleString()} (${((data.converted / data.users) * 100).toFixed(1)}%)` },
    { label: 'Largest re-attribution', compute: () => `${label(data.swingChannel)} ${data.swingLast} → ${data.swingMarkov}`, tone: 'warn' },
    { label: 'Campaign effect', compute: () => `${data.ate > 0 ? '+' : ''}${pts(data.ate)} (CI ${(data.ateLow * 100).toFixed(1)}–${(data.ateHigh * 100).toFixed(1)})`, tone: data.ateLow > 0 ? 'ok' : 'muted' },
    { label: `Blended LTV:CAC at M${data.ltvHorizon}`, compute: () => data.ltvToCac.toFixed(2), tone: data.ltvToCac >= 1 ? 'ok' : 'danger' }
  ],
  tour: [
    { selector: '.gae-note', title: 'What this page is', body: 'A report the CI pipeline generated by running the package on a seeded synthetic event stream with a known causal structure. The same command reproduces it.', action: () => {} },
    { selector: '#s-attribution', title: 'Last touch flatters the closer', body: `Compare the last-touch and Markov columns. ${label(data.swingChannel)} moves from ${data.swingLast} to ${data.swingMarkov} credited enrolments: the largest swing on this run, and the difference between rewarding the channel that was there at the end and the channel whose removal would cost the most. The last table row shows neither ranking matches the generator's true effects well: attribution is accounting, not cause.`, action: () => {} },
    { selector: '#s-cohorts', title: 'Retention, not sign-ups', body: 'The heatmap reads left to right within a cohort. Blank cells are months that cohort has not lived through yet; the report never extrapolates them.', action: () => {} },
    { selector: '#s-uplift', title: 'A randomised campaign, read by segment', body: `The average effect is ${pts(data.ate)}. The ${label(data.bestSegment)} segment carries it at ${pts(data.bestSegmentUplift)}; the others show intervals that include zero. Targeting by segment beats treating everyone, which is what the Qini curve draws.`, action: () => {} },
    { selector: '#s-economics', title: 'Cost and return per channel', body: `Acquisition cost uses the Markov credits above; lifetime value comes from the cohort curve at month ${data.ltvHorizon}. ${label(data.worstChannel)} has the weakest LTV:CAC on this run, and the blended ratio is ${data.ltvToCac.toFixed(2)}.`, action: () => {} }
  ]
});
shell.refreshKpis();
